export const SPAM_REPORT_REPORT_SPAM_START = 'SPAM_REPORT_REPORT_SPAM_START';
export const SPAM_REPORT_REPORT_SPAM_SUCCESS = 'SPAM_REPORT_REPORT_SPAM_SUCCESS';
export const SPAM_REPORT_REPORT_SPAM_CANCEL = 'SPAM_REPORT_REPORT_SPAM_CANCEL';
export const SPAM_REPORT_REPORT_SPAM_ERROR = 'SPAM_REPORT_REPORT_SPAM_ERROR';

